# Problema II

Queremos estimar la función generatriz de momentos (transformada de Laplace)

$$
\phi_{X}(u):=E[e^{uX}], u \in \mathbb{R}
$$

de una variable aleatoria $X\sim N(0,\sigma^{2})$ utilizando una muestra de tamaño M de copias i.i.d. de X. El parámetro $\sigma^{2}$ es desconocido.

1.  Demostrar que para $X\sim N(0,\sigma^{2})$ se cumple: 
    $$
      \mathbb{E}[e^{uX}]=e^{\sigma^{2}u^{2}/2}
    $$

2.  Comparar la precisión de los siguientes dos estimadores de $\phi_{X}(u)$:\
    ***Estimador directo:*** 
    $$
      \phi_{1,M}(u):=\frac{1}{M}\sum_{m=1}^{M}e^{uX_{m}}.
    $$ 
    ***Estimador en dos etapas:***
    a)  Estimar $\sigma^{2}$ mediante: 
        $$
           \sigma_{M}^{2}=\frac{1}{M-1}\sum_{m=1}^{M}(X_{m}-\bar{X})^{2}
        $$
    b)  Construir el estimador `plug-in` de $\phi_{X}(u)$ 
        $$
          \phi_{2,M}(u):=e^{\frac{u^{2}}{2}\sigma_{M}^{2}}
        $$

Construir intervalos de confianza asintóticos para ambos estimadores de $\phi_{X}(u)$. Interpretar los resultados obtenidos.

## Parte 1

\begin{aligned}

\mathbb{E} \left[ e^{uX} \right] 

&= \int_{-\infty}^{+\infty} e^{ux}\frac{1}{\sqrt{2\pi\sigma^2}}e^{\frac{-x^2}{2\sigma^2}}dx \\ 

&= \int_{-\infty}^{+\infty} \frac{1}{\sqrt{2\pi\sigma^2}}e^{\frac{-1}{2\sigma^2}[x^2 - 2\sigma^2ux]}dx \\

&= \int_{-\infty}^{+\infty} \frac{1}{\sqrt{2\pi\sigma^2}}e^{\frac{-1}{2\sigma^2}[x^2 - 2\sigma^2ux + (\sigma^2u)^2 - (\sigma^2u)^2]} dx \\

&=  \int_{-\infty}^{+\infty} \frac{1}{\sqrt{2\pi\sigma^2}}e^{\frac{-1}{2\sigma^2}[(x -u\sigma^2)^2 -(u\sigma^2)^2]}dx \\

&= e^\frac{(u\sigma^2)^2}{2\sigma^2}\int_{-\infty}^{+\infty}\frac{1}{\sqrt{2\pi\sigma^2}}e^\frac{-(x-u\sigma^2)^2}{2\sigma^2}\\

&\text{Lo que nos queda dentro de la integral es la densidad de una } \mathcal{N}(u\sigma^2, \sigma^2) \text{ por lo que integra 1} \\

&= e^\frac{u^2\sigma^2}{2}

\end{aligned}

## Parte 2

### Parte a: Estimador directo

Verificamos que el indicador sea insesgado

$$    
\mathbb{E} \bigr[ \phi_{1,M}(u) \bigl]
    = \mathbb{E} \Bigr[ \frac{1}{M}\sum_{m=1}^M e^{uX_m} \Bigl] \quad 
    \overset{\text{linealidad}}{=} \frac{1}{M}M\mathbb{E}\bigr[ e^{uX} \bigl] \quad 
    \overset{\text{parte 1}}{=} e^\frac{u^2\sigma^2}{2}
$$
Estudiamos su varianza

$$
\begin{aligned}
  \text{Var} \bigr[ \phi_{1,M}(u) \bigl] 
    &= \text{Var}\Bigr[ \frac{1}{M}\sum_{m=1}^M e^{uX_m} \Bigl] \\
    &= \frac{1}{M^2}\text{Var}\Bigr[\sum_{m=1}^M e^{uX_m} \Bigl] \\
    &= \frac{1}{M}\text{Var}\bigr[e^{uX} \bigl] \\
    &= \frac{1}{M} \Bigr[ \mathbb{E}\bigr[(e^{uX})^2 \bigl] - \mathbb{E}[e^{uX}]^2   \Bigl] \\
    &= \frac{1}{M} \Bigr[ \mathbb{E}\bigr[e^{2uX} \bigl] - \mathbb{E}[e^{uX}]^2   \Bigl] \\
  \text{(parte 1)}  &= \frac{1}{M} \Bigr[ e^{2u^2\sigma^2} - e^{u^2\sigma^2} \Bigl] \\
    &= \frac{1}{M} \Bigr[ e^{u^2\sigma^2}(e^{u^2\sigma^2} - 1) \Bigl] 
\end{aligned}
$$

### Parte b: Estimador en dos etapas

Para estudiar la distribución asintótica del estimador $\phi_{2,M}(u)$ de $E\left[e^{uX}\right] = e^{\frac{u^2}{2} \sigma^2}$. utilizaremos el siguiente teorema (denominado `método delta`): 

Si

$$
\sqrt{M}(T_M - \theta) \xrightarrow[M \to \infty]{d} Y \quad Y \sim N(0, \tau^2),
$$

entonces

$$
\sqrt{M}\left[f(T_M) - f(\theta)\right] \xrightarrow[M \to \infty]{d} W \quad W \sim N\left(0, \tau^2 [f^{\prime}(\theta)]^2\right),
$$

siempre que $f^{\prime}(\theta)$ exista y sea distinta de cero.

En este ejercicio: 

$$
\begin{aligned}
&\bullet \quad T_M := \sigma^2_M, \quad \theta = \sigma^{2}, \quad \text{y} \quad 
\sqrt{M}(\sigma^2_M - \sigma^{2}) \xrightarrow[M \to \infty]{d} Y, \quad 
Y \sim \mathcal{N}(0, 2 \sigma^{4}); \\
&\bullet \quad \phi_{2,M}(u) := e^{\frac{u^2}{2} \sigma^2_M} = f(\sigma^2_M), \quad \text{y} \quad 
f^{\prime}(\sigma^2) = \frac{u^{2}}{2} e^{\frac{u^{2}}{2} \sigma^2}.
\end{aligned}
$$


Por lo tanto, $\sqrt{M} \, \left[\phi_{2,M}(u) -  E\left[e^{uX}\right] \right] \xrightarrow[M \to \infty]{d} W \,,  \: W \sim N(0, 2 \sigma^{4} \frac{u^{4}}{4} e^{u^2 \sigma^2}).$ 

Si consideramos el desarrollo $e^{y} = 1 + y + \frac{y^{2}}{2} +  \cdots$, con $y = u^2 \sigma^2$, se obtiene 
$e^{u^2\sigma^2} - 1 = u^2 \sigma^2 +  \frac{(u^2 \sigma^2)^{2}}{2} + \cdots$.

Finalmente, observamos que

$$
Var(e^{uX}) =  e^{u^2 \sigma^2} (  e^{u^2 \sigma^2} -1) >  e^{u^2 \sigma^2} \left( u^2 \sigma^2  + \frac{(u^2 \sigma^2)^2}{2}  \right) > e^{u^2 \sigma^2} \frac{(u^2 \sigma^2)^2}{2} 
$$.
